# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryHic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter', models.CharField(default='', max_length=60, null=True)),
                ('bedtype', models.CharField(default='', max_length=60, null=True)),
                ('tallyyear', models.IntegerField()),
            ],
            options={
                'ordering': ('shelter',),
            },
        ),
        migrations.CreateModel(
            name='HistoryPitSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table', models.CharField(default='', max_length=17, null=True)),
                ('Population', models.CharField(default='', max_length=32, null=True)),
                ('SubPopulation', models.CharField(default='', max_length=37, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Value', models.CharField(default='', max_length=11, null=True)),
            ],
            options={
                'ordering': ('Table',),
            },
        ),
    ]
