# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyhic',
            options={'ordering': ('Shelter',)},
        ),
        migrations.RenameField(
            model_name='historyhic',
            old_name='bedtype',
            new_name='BedType',
        ),
        migrations.RenameField(
            model_name='historyhic',
            old_name='shelter',
            new_name='Shelter',
        ),
        migrations.RemoveField(
            model_name='historyhic',
            name='tallyyear',
        ),
        migrations.AddField(
            model_name='historyhic',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
