# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0002_auto_20161211_0319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryHic',
            new_name='HistoryHicAPI',
        ),
        migrations.RenameModel(
            old_name='HistoryPitSummary',
            new_name='HistoryPitSummaryAPI',
        ),
    ]
