# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_auto_20161212_0615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PitSubpopulationsAPI',
            new_name='HistoryPitSubpopulationsAPI',
        ),
    ]
