# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0005_auto_20161212_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyhicapi',
            name='Value',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='historypitsubpopulationsapi',
            name='Value',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='historypitsummaryapi',
            name='Value',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
