# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0006_auto_20161212_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypitsubpopulationsapi',
            name='Table',
            field=models.CharField(default='', max_length=18, null=True),
        ),
    ]
